### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by fhyoga** [videomanagertools/scraper#1]
#### roadmap

 - [x] 匹配有效番号 (持续优化)
- [x] 批处理进度 done
- [x] tree 结构优化 p0 done
- [x] 抽出进度 modal done
- [x] 操作反馈 done
- [x] 搜刮错误标记手动 p0 done
- [x] 无效路径过滤 done
- [x] 目录格式化 p0 done
- [x] 信息回填(需要修改Model结构)
- [x] 边界处理（持续）
- [x] 使用 hooks 重写
- [x] 补全ts类型约束
- [x] 切换信息源 p1
- [ ] 爬取改为并发
- [x] proxy代理
- [x] 打标签
- [ ] 日志
- [ ] 错误任务重试
- [ ] 大量目录下的性能优化
- [ ] 查询，预览，写入，格式化功能分离
- [ ] CI报错

**Comment by fhyoga** [comment]
https://github.com/videomanagertools/scraper/projects
